exp_name: 'bigger-G-smallerLR-D'

seed: 42
device: 'cuda'
img_channels: 1
img_size: 28
num_classes: 10
size_train_set: 1.0
z_dim: 100

gen_z_fcs: [100, 200, 512]
gen_y_fcs: [10, 200, 512]
gen_j_fcs: [1024, 1200, 784]

dis_z_fcs: [784, 200]
dis_y_fcs: [10, 200]
dis_j_fcs: [400, 784, 200, 1]

dropout_rate: 0.2
lr_G: 0.1
lr_D: 0.01
weight_decay: 0.01
num_epochs: 100
batch_size: 16
transform_train: True
workers: 8